spring.application.name=WaitLess_Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/waitless_app_db?sslmode=disable

spring.datasource.username=postgres
spring.datasource.password=TYU123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.address=0.0.0.0

jwt.secret=waitless_jwt_secret_key_1234567890
jwt.expiration=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nextupvqms@gmail.com
spring.mail.password=ikigfhuafeikhtyc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
